/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Project API
 * OpenAPI spec version: 1.0
 */
export type ScammerDemoProfileItemStarRate =
    (typeof ScammerDemoProfileItemStarRate)[keyof typeof ScammerDemoProfileItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerDemoProfileItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export type ScammerDemoProfileItemCategory =
    (typeof ScammerDemoProfileItemCategory)[keyof typeof ScammerDemoProfileItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerDemoProfileItemCategory = {
    INVESTMENTS: 'INVESTMENTS',
    TRADER: 'TRADER',
    CAPPER: 'CAPPER',
    GAME: 'GAME',
    CASINO: 'CASINO',
    EXCHANGES: 'EXCHANGES',
} as const;

export type ScammerDemoProfileItemVisible =
    (typeof ScammerDemoProfileItemVisible)[keyof typeof ScammerDemoProfileItemVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerDemoProfileItemVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface ScammerDemoProfileItem {
    id: number;
    url: string;
    name: string;
    avatar_url: string;
    positionTop: number;
    starRate: ScammerDemoProfileItemStarRate;
    rate: number;
    reports: number;
    reviews: number;
    shortDescription: string;
    tgUsername: string;
    category: ScammerDemoProfileItemCategory;
    visible: ScammerDemoProfileItemVisible;
}

export interface ScammerDemoProfileItemList {
    items: ScammerDemoProfileItem[];
}

export type ScammerProfileItemStarRate = (typeof ScammerProfileItemStarRate)[keyof typeof ScammerProfileItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export type ScammerProfileItemVisible = (typeof ScammerProfileItemVisible)[keyof typeof ScammerProfileItemVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileItemVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export type ScammerProfileItemCategory = (typeof ScammerProfileItemCategory)[keyof typeof ScammerProfileItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileItemCategory = {
    INVESTMENTS: 'INVESTMENTS',
    TRADER: 'TRADER',
    CAPPER: 'CAPPER',
    GAME: 'GAME',
    CASINO: 'CASINO',
    EXCHANGES: 'EXCHANGES',
} as const;

export interface ScammerProfileItem {
    id: number;
    url: string;
    name: string;
    avatar_url: string;
    positionTop: number;
    starRate: ScammerProfileItemStarRate;
    rate: number;
    subcribers: number;
    reports: number;
    reviews: number;
    shortDescription: string;
    tgUsername: string;
    visible: ScammerProfileItemVisible;
    category: ScammerProfileItemCategory;
    createdAt: Date;
    reviewDate: Date;
    profileLikes: number;
    profileViews: number;
    about: string;
}

export type ScammerCommentItemStarRate = (typeof ScammerCommentItemStarRate)[keyof typeof ScammerCommentItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerCommentItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export interface ScammerCommentItem {
    id: number;
    name: string;
    comment: string;
    projectId: number;
    date: Date;
    starRate: ScammerCommentItemStarRate;
}

export interface ScammerCommentList {
    items: ScammerCommentItem[];
}

export interface PostPreviewItem {
    id: number;
    url: string;
    title: string;
    likes: number;
    views: number;
    readTime: number;
    date: Date;
}

export interface PostPreviewList {
    items: PostPreviewItem[];
}

export interface PostItem {
    id: number;
    url: string;
    title: string;
    post: string;
    likes: number;
    views: number;
    readTime: number;
    date: Date;
}

export type PostCommentItemStarRate = (typeof PostCommentItemStarRate)[keyof typeof PostCommentItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostCommentItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export interface PostCommentItem {
    id: number;
    name: string;
    comment: string;
    postId: number;
    date: Date;
    starRate: PostCommentItemStarRate;
}

export interface PostCommentsList {
    items: PostCommentItem[];
}

export type HeaderBannerItemBannerType = (typeof HeaderBannerItemBannerType)[keyof typeof HeaderBannerItemBannerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HeaderBannerItemBannerType = {
    YOUTUBE: 'YOUTUBE',
    LAWYER: 'LAWYER',
} as const;

export interface HeaderBannerItem {
    id: number;
    url: string;
    bannerType: HeaderBannerItemBannerType;
}

export interface ImagesBannerItem {
    id: number;
    name: string;
    url: string;
    image: string;
}

export interface ImagesBannerList {
    items: ImagesBannerItem[];
}

export type LawyerBannerVisible = (typeof LawyerBannerVisible)[keyof typeof LawyerBannerVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LawyerBannerVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface LawyerBanner {
    id: number;
    visible: LawyerBannerVisible;
    name: string;
    title: string;
    avatar: string;
    description: string;
    reviews: number;
    reports: number;
    tgUrl: string;
    detailsUrl: string;
}

/**
 * @nullable
 */
export type LawyerBannerItemItems = LawyerBanner | null;

export interface LawyerBannerItem {
    /** @nullable */
    items: LawyerBannerItemItems;
}

export type YoutubeLayoutItemVisible = (typeof YoutubeLayoutItemVisible)[keyof typeof YoutubeLayoutItemVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const YoutubeLayoutItemVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface YoutubeLayoutItem {
    id: number;
    visible: YoutubeLayoutItemVisible;
    name: string;
    description: string;
    videoId: string;
    tgUrl: string;
    youtubeUrl: string;
}

export type LawyerLayoutItemVisible = (typeof LawyerLayoutItemVisible)[keyof typeof LawyerLayoutItemVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LawyerLayoutItemVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface LawyerLayoutItem {
    id: number;
    visible: LawyerLayoutItemVisible;
    name: string;
    description: string;
    avatar: string;
    tgUrl: string;
    detailsUrl: string;
}

export interface FooterStripItem {
    id: number;
    youtubeUrl: string;
    tgUrl: string;
}

export interface ReviewRequestDto {
    /** @maxLength 30 */
    username: string;
    /** @maxLength 30 */
    userContact: string;
    /** @maxLength 500 */
    comment: string;
    /** @maxLength 30 */
    projectName: string;
    /** @maxLength 30 */
    projectUrl: string;
}

export type LawyerProfileVisible = (typeof LawyerProfileVisible)[keyof typeof LawyerProfileVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LawyerProfileVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface LawyerProfile {
    id: number;
    profile: string;
    visible: LawyerProfileVisible;
}

/**
 * @nullable
 */
export type LawyerProfileItemItems = LawyerProfile | null;

export interface LawyerProfileItem {
    /** @nullable */
    items: LawyerProfileItemItems;
}

export interface NewsPreviewItem {
    id: number;
    url: string;
    avatar: string;
    title: string;
    views: number;
    date: Date;
}

export interface NewsPreviewList {
    items: NewsPreviewItem[];
}

export interface NewsItem {
    id: number;
    url: string;
    title: string;
    avatar: string;
    news: string;
    likes: number;
    views: number;
    date: Date;
}

export type NewsCommentItemStarRate = (typeof NewsCommentItemStarRate)[keyof typeof NewsCommentItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewsCommentItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export interface NewsCommentItem {
    id: number;
    name: string;
    comment: string;
    newsId: number;
    date: Date;
    starRate: NewsCommentItemStarRate;
}

export interface NewsCommentList {
    items: NewsCommentItem[];
}
