/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Project API
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseInfiniteQueryResult,
    DefinedUseQueryResult,
    InfiniteData,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseInfiniteQueryOptions,
    UseInfiniteQueryResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query';

import type { PostItem, PostPreviewList } from '../api.schemas';

import { axiosCall } from '.././api.axios';
import type { ErrorType } from '.././api.axios';

export const postGetList = (signal?: AbortSignal) => {
    return axiosCall<PostPreviewList>({ url: `/post/list`, method: 'GET', signal });
};

export const getPostGetListQueryKey = () => {
    return [`/post/list`] as const;
};

export const getPostGetListInfiniteQueryOptions = <
    TData = InfiniteData<Awaited<ReturnType<typeof postGetList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getPostGetListQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postGetList>>> = ({ signal }) => postGetList(signal);

    return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof postGetList>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostGetListInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postGetList>>>;
export type PostGetListInfiniteQueryError = ErrorType<unknown>;

export function usePostGetListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetList>>>,
    TError = ErrorType<unknown>,
>(options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>> &
        Pick<
            DefinedInitialDataOptions<
                Awaited<ReturnType<typeof postGetList>>,
                TError,
                Awaited<ReturnType<typeof postGetList>>
            >,
            'initialData'
        >;
}): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>> &
        Pick<
            UndefinedInitialDataOptions<
                Awaited<ReturnType<typeof postGetList>>,
                TError,
                Awaited<ReturnType<typeof postGetList>>
            >,
            'initialData'
        >;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePostGetListInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetList>>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getPostGetListInfiniteQueryOptions(options);

    const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getPostGetListQueryOptions = <
    TData = Awaited<ReturnType<typeof postGetList>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>>;
}) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getPostGetListQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postGetList>>> = ({ signal }) => postGetList(signal);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof postGetList>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostGetListQueryResult = NonNullable<Awaited<ReturnType<typeof postGetList>>>;
export type PostGetListQueryError = ErrorType<unknown>;

export function usePostGetList<TData = Awaited<ReturnType<typeof postGetList>>, TError = ErrorType<unknown>>(options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>> &
        Pick<
            DefinedInitialDataOptions<
                Awaited<ReturnType<typeof postGetList>>,
                TError,
                Awaited<ReturnType<typeof postGetList>>
            >,
            'initialData'
        >;
}): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetList<TData = Awaited<ReturnType<typeof postGetList>>, TError = ErrorType<unknown>>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>> &
        Pick<
            UndefinedInitialDataOptions<
                Awaited<ReturnType<typeof postGetList>>,
                TError,
                Awaited<ReturnType<typeof postGetList>>
            >,
            'initialData'
        >;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetList<TData = Awaited<ReturnType<typeof postGetList>>, TError = ErrorType<unknown>>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePostGetList<TData = Awaited<ReturnType<typeof postGetList>>, TError = ErrorType<unknown>>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetList>>, TError, TData>>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getPostGetListQueryOptions(options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const postGetOne = (url: string, signal?: AbortSignal) => {
    return axiosCall<PostItem>({ url: `/post/one/${url}`, method: 'GET', signal });
};

export const getPostGetOneQueryKey = (url: string) => {
    return [`/post/one/${url}`] as const;
};

export const getPostGetOneInfiniteQueryOptions = <
    TData = InfiniteData<Awaited<ReturnType<typeof postGetOne>>>,
    TError = ErrorType<unknown>,
>(
    url: string,
    options?: { query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getPostGetOneQueryKey(url);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postGetOne>>> = ({ signal }) => postGetOne(url, signal);

    return { queryKey, queryFn, enabled: !!url, ...queryOptions } as UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof postGetOne>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostGetOneInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof postGetOne>>>;
export type PostGetOneInfiniteQueryError = ErrorType<unknown>;

export function usePostGetOneInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetOne>>>,
    TError = ErrorType<unknown>,
>(
    url: string,
    options: {
        query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof postGetOne>>,
                    TError,
                    Awaited<ReturnType<typeof postGetOne>>
                >,
                'initialData'
            >;
    },
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetOneInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetOne>>>,
    TError = ErrorType<unknown>,
>(
    url: string,
    options?: {
        query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof postGetOne>>,
                    TError,
                    Awaited<ReturnType<typeof postGetOne>>
                >,
                'initialData'
            >;
    },
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetOneInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetOne>>>,
    TError = ErrorType<unknown>,
>(
    url: string,
    options?: { query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> },
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePostGetOneInfinite<
    TData = InfiniteData<Awaited<ReturnType<typeof postGetOne>>>,
    TError = ErrorType<unknown>,
>(
    url: string,
    options?: { query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> },
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getPostGetOneInfiniteQueryOptions(url, options);

    const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}

export const getPostGetOneQueryOptions = <TData = Awaited<ReturnType<typeof postGetOne>>, TError = ErrorType<unknown>>(
    url: string,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> },
) => {
    const { query: queryOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getPostGetOneQueryKey(url);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof postGetOne>>> = ({ signal }) => postGetOne(url, signal);

    return { queryKey, queryFn, enabled: !!url, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof postGetOne>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PostGetOneQueryResult = NonNullable<Awaited<ReturnType<typeof postGetOne>>>;
export type PostGetOneQueryError = ErrorType<unknown>;

export function usePostGetOne<TData = Awaited<ReturnType<typeof postGetOne>>, TError = ErrorType<unknown>>(
    url: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof postGetOne>>,
                    TError,
                    Awaited<ReturnType<typeof postGetOne>>
                >,
                'initialData'
            >;
    },
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetOne<TData = Awaited<ReturnType<typeof postGetOne>>, TError = ErrorType<unknown>>(
    url: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof postGetOne>>,
                    TError,
                    Awaited<ReturnType<typeof postGetOne>>
                >,
                'initialData'
            >;
    },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePostGetOne<TData = Awaited<ReturnType<typeof postGetOne>>, TError = ErrorType<unknown>>(
    url: string,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePostGetOne<TData = Awaited<ReturnType<typeof postGetOne>>, TError = ErrorType<unknown>>(
    url: string,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof postGetOne>>, TError, TData>> },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getPostGetOneQueryOptions(url, options);

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };

    query.queryKey = queryOptions.queryKey;

    return query;
}
