/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Project Admin API
 * OpenAPI spec version: 1.0
 */
export interface AuthDto {
    login: string;
    password: string;
}

export interface AuthResponse {
    authToken: string;
}

export type ScummerStarRate = (typeof ScummerStarRate)[keyof typeof ScummerStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScummerStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export interface ScammerCreateDto {
    url: string;
    name: string;
    avatar_url: string;
    starRate: ScummerStarRate;
    rate: number;
    subcribers: number;
    reports: number;
    reviews: number;
    shortDescription: string;
    tgUsername: string;
    reviewDate: Date;
}

export interface ScammerDemoProfileItem {
    id: number;
    name: string;
    positionTop: number;
}

export interface ScammerDemoProfileItemList {
    items: ScammerDemoProfileItem[];
}
