/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Project Admin API
 * OpenAPI spec version: 1.0
 */
export interface AuthDto {
    login: string;
    password: string;
}

export interface AuthResponse {
    authToken: string;
}

export type ScummerStarRate = (typeof ScummerStarRate)[keyof typeof ScummerStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScummerStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export type ScummerCategory = (typeof ScummerCategory)[keyof typeof ScummerCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScummerCategory = {
    INVESTMENTS: 'INVESTMENTS',
    TRADER: 'TRADER',
    CAPPER: 'CAPPER',
    GAME: 'GAME',
    CASINO: 'CASINO',
    EXCHANGES: 'EXCHANGES',
} as const;

export interface ScammerCreateDto {
    url: string;
    name: string;
    avatar_url: string;
    starRate: ScummerStarRate;
    category: ScummerCategory;
    rate: number;
    subcribers: number;
    reports: number;
    reviews: number;
    shortDescription: string;
    tgUsername: string;
    reviewDate: Date;
}

export type ScammerDemoProfileItemCategory =
    (typeof ScammerDemoProfileItemCategory)[keyof typeof ScammerDemoProfileItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerDemoProfileItemCategory = {
    INVESTMENTS: 'INVESTMENTS',
    TRADER: 'TRADER',
    CAPPER: 'CAPPER',
    GAME: 'GAME',
    CASINO: 'CASINO',
    EXCHANGES: 'EXCHANGES',
} as const;

export type ScammerDemoProfileItemVisible =
    (typeof ScammerDemoProfileItemVisible)[keyof typeof ScammerDemoProfileItemVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerDemoProfileItemVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface ScammerDemoProfileItem {
    id: number;
    name: string;
    positionTop: number;
    tgUsername: string;
    category: ScammerDemoProfileItemCategory;
    visible: ScammerDemoProfileItemVisible;
}

export interface ScammerDemoProfileItemList {
    items: ScammerDemoProfileItem[];
}

export type ScammerProfileItemStarRate = (typeof ScammerProfileItemStarRate)[keyof typeof ScammerProfileItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export type ScammerProfileItemVisible = (typeof ScammerProfileItemVisible)[keyof typeof ScammerProfileItemVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileItemVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export type ScammerProfileItemCategory = (typeof ScammerProfileItemCategory)[keyof typeof ScammerProfileItemCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileItemCategory = {
    INVESTMENTS: 'INVESTMENTS',
    TRADER: 'TRADER',
    CAPPER: 'CAPPER',
    GAME: 'GAME',
    CASINO: 'CASINO',
    EXCHANGES: 'EXCHANGES',
} as const;

export interface ScammerProfileItem {
    id: number;
    url: string;
    name: string;
    avatar_url: string;
    positionTop: number;
    starRate: ScammerProfileItemStarRate;
    rate: number;
    subcribers: number;
    reports: number;
    reviews: number;
    shortDescription: string;
    tgUsername: string;
    visible: ScammerProfileItemVisible;
    category: ScammerProfileItemCategory;
    createdAt: Date;
    reviewDate: Date;
    profileLikes: number;
    profileViews: number;
    about: string;
}

export type ScammerProfileAboutVisible = (typeof ScammerProfileAboutVisible)[keyof typeof ScammerProfileAboutVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerProfileAboutVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface ScammerProfileAbout {
    visible: ScammerProfileAboutVisible;
    profileLikes: number;
    profileViews: number;
    about: string;
}

export type ScummerVisible = (typeof ScummerVisible)[keyof typeof ScummerVisible];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScummerVisible = {
    VISIBLE: 'VISIBLE',
    HIDDEN: 'HIDDEN',
} as const;

export interface ScammerEditAboutDto {
    visible: ScummerVisible;
    profileLikes: number;
    profileViews: number;
    about: string;
}

export interface ScammerUpdatePositionItemDto {
    id: number;
    positionTop: number;
}

export interface ScammerUpdatePositionListDto {
    items: ScammerUpdatePositionItemDto[];
}

export type CommentStarRate = (typeof CommentStarRate)[keyof typeof CommentStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export interface ScammerCreateComment {
    name: string;
    comment: string;
    date: Date;
    starRate: CommentStarRate;
}

export type ScammerCommentItemStarRate = (typeof ScammerCommentItemStarRate)[keyof typeof ScammerCommentItemStarRate];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ScammerCommentItemStarRate = {
    NUMBER_1: '1',
    NUMBER_2: '2',
    NUMBER_3: '3',
    NUMBER_4: '4',
    NUMBER_5: '5',
} as const;

export interface ScammerCommentItem {
    id: number;
    name: string;
    comment: string;
    projectId: number;
    date: Date;
    starRate: ScammerCommentItemStarRate;
}

export interface ScammerCommentList {
    items: ScammerCommentItem[];
}

export interface PostCreatePreviewDto {
    url: string;
    title: string;
    likes: number;
    views: number;
    readTime: number;
    date: Date;
}

export interface PostEditContentDto {
    post: string;
}

export interface PostPreviewItem {
    id: number;
    title: string;
    likes: number;
    views: number;
    date: Date;
}

export interface PostPreviewList {
    items: PostPreviewItem[];
}

export interface PostItem {
    id: number;
    url: string;
    title: string;
    post: string;
    likes: number;
    views: number;
    readTime: number;
    date: Date;
}
